dist: xenial

language: python
python:
  - "3.8"

git:
  depth: 1

install:
  - pip install .

before_script:
  - wget http://download.geonames.org/export/dump/cities15000.zip
  - unzip -o cities15000.zip -d ./dataset/
  - pip install ruamel.yaml

# command to run tests
script:
  - pytest test

